# Generated by Django 3.2.9 on 2021-11-14 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Заголовок')),
                ('video_link', models.URLField(blank=True, default='', null=True, verbose_name='Ссылка на видео')),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='reviews', verbose_name='Фото')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Текст отзыва')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('comment', models.CharField(blank=True, default='', max_length=220, verbose_name='Комментарий')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewiews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-published'],
            },
        ),
    ]
